<default: &default
  adapter:  postgresql
  encoding: unicode
  host: 0.0.0.0
  username: benjamin_balanger
  password: Lavoisier8

development:
 <<: *default
 database: captain_dev

test:
 <<: *default
 database: captain_test

production:
 <<: *default
 database: captain_prod
